### ISSUE TITLE
whatever this is

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/Opencomputers-servertine#2]
this happens everytime i log in:
![2023-02-06_17 38 03](https://user-images.githubusercontent.com/123119027/217103742-992f36a9-e65e-47e3-8a06-a9b78fbdf7d9.png)
cryptKey = {6, 1, 5, 7, 2}
port = 9279

**Comment by enderman-2009** [comment]
nvm its my worstt ennemy the relay button again

**Comment by cadergator10** [comment]
> nvm its my worst ennemy the relay button again

![demoman-tf2](https://user-images.githubusercontent.com/75097681/217126835-d4f3f120-5443-4989-ba86-9dbc51b9bd34.gif)
